### ISSUE TITLE
Issues with DFR in DCS

### ISSUE THREAD

**Issue by ytdlder** [mbucchia/Quad-Views-Foveated#10]
Hi, I've been successful using OpenXR, PimaxOpenXR and DCS for quite a while now with my Crystal; works wonderfully!!

And finally Eye Tracking in the Crystal released. I've calibrated several times and it works reasonably well and after installing QuadViews (newest 1.1.1) I've reset the OpenXRToolkit settings as described.
I've made sure it works by making sure the API is enabled and loaded as well as by testing it with a setting of "peripheral_multiplier=0.1" -> yep, it works really well!

And the FPS... woah, I really don't want to play without it ever again :-)

2 Problems as far as I can see:
-  I'm currently playing the P-51D and for whatever reason, there are no (red) tracers visible when shooting the gun
- but more importantly, when playing the mission "Red rover, red rover", and flying lower, some weird **picture in picture in picture** error happens (I hope I can post screenshots here; worked after resizing....)
![DCS World_20230914_110733_R](https://github.com/mbucchia/Quad-Views-Foveated/assets/26724958/034c2efd-6d46-4522-af4b-3aab065b175f)
![DCS World_20230914_110737_L](https://github.com/mbucchia/Quad-Views-Foveated/assets/26724958/5c17e62e-4db6-4293-bf22-ed21efffb379)
![DCS World_20230914_110737_R](https://github.com/mbucchia/Quad-Views-Foveated/assets/26724958/a8c0047c-fbe3-4075-bf23-c220aca458b7)
![DCS World_20230914_110733_L](https://github.com/mbucchia/Quad-Views-Foveated/assets/26724958/eec65aff-b057-4b94-a428-93b7112a3d9a)

I have no problems when I disable QuadViews (via SteamVR-Settings)

**Comment by ytdlder** [comment]
I've tried recreating this problem when using DCS via SteamVR, but I don't think DFR worked... the FPS were really low (a bit lower then with OpenXR without DFR).
I've set DFR to Maximum in the Pimax client. Well, Pimax isn't known for quality translations, so maybe I have to use DFR Minimum?

**Comment by ytdlder** [comment]
Well... shit.
To test DFR with SteamVR, I've pressed the button "Set SteamVR as the OpenXR Runtime" in the SteamVR settings (I think it was OpenXR before), and now I don't know how to switch back...
![image](https://github.com/mbucchia/Quad-Views-Foveated/assets/26724958/2b4f2bdc-f2ba-4ac3-ae67-25fa5f4cd869)

**Comment by ytdlder** [comment]
Ok, I've managed to go back to the Pimax-OpenXR runtime via the registry:
```
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenXR\1
ActiveRuntime = C:\Program Files\PimaxXR\pimax-openxr.json
```

But I've played this mission now about a dozen time and the error always pops up...

I'm gonna try some other missions/campaigns to see if I can reproduce the problem there.

**Comment by ytdlder** [comment]
I've now played the Challenge Campaign and... nothing.

- Until **mission 8** "Fly Under Bridges" -> it happens right after the second bridge

- The next time happens right in **mission 9**: right after flying through gate 16 (hard left turn), meaning you won't clearly see gate 17 and thus cannot really finish that mission.

**Comment by mbucchia** [comment]
Your issue is cause by Lens Effect (because you did not read the setup instructions carefully)

https://github.com/mbucchia/Quad-Views-Foveated/wiki#dcs-world

![Screenshot_20230913_205313_Chrome](https://github.com/mbucchia/Quad-Views-Foveated/assets/69611560/4a2e6aba-d010-464f-8164-b052fada62e5)

**Comment by ytdlder** [comment]
I do have ReShade installed; but only on the single-thread exe/path.
I use MT for VR, so that can't do anything?

**Comment by ytdlder** [comment]
I'm gonna uninstall Reshade and check the DCS settings again; will get back to you asap.

**Comment by ytdlder** [comment]
Well... shit. You were right.
DFR is such a performance boost, that I tested my "2D settings", which included Lens Effects. So they actually were enabled.

I've now tried turning it off and it really seems to have been the thing causing this problem.

THANK YOU!! I was really worried something fundamentally wrong with the Pimax driver or something.
