### ISSUE TITLE
Tracers not or barely visible with DFR in DCS

### ISSUE THREAD

**Issue by ytdlder** [mbucchia/Quad-Views-Foveated#11]
So, the second issue I'm kinda concerned with: gauging my own shots without tracers is pretty rough; they are invisible except when very far away. But also tracer fire from AAA  is sometimes hard to see; probably depends on the distance and the angle of the tracer fire.

It's both eyes; I've checked.
I've tried this with Stable (Steam) and a clean Beta install. Same mission, Same configs.

The following...
- 'VR' -> 'Bloom effect'
- 'System' -> 'Lens Effects'

- Toolkit 'Foveated Rendering'
- Toolkit 'Field of view' override and 'Zoom'
- Toolkit 'Turbo mode'
...are all disabled

Hopefully you've got an idea what this problem could be like?

Here are screenshots with QuadViews enabled:

![1](https://github.com/mbucchia/Quad-Views-Foveated/assets/26724958/527ff5ef-3b5b-49b9-8c48-62d3f7af6fc1)
![2](https://github.com/mbucchia/Quad-Views-Foveated/assets/26724958/3d70e5dc-4d06-4209-95af-8b2c6fcf006f)
![3](https://github.com/mbucchia/Quad-Views-Foveated/assets/26724958/b5c85e9a-2361-4746-acda-4211852cde48)
![4](https://github.com/mbucchia/Quad-Views-Foveated/assets/26724958/708a9989-7748-44f3-bd5e-16c0b3f0236c)

And here's how it should look like (QuadViews disabled):
![1](https://github.com/mbucchia/Quad-Views-Foveated/assets/26724958/e2853081-5c73-4a03-b323-18586a1542e0)
![2](https://github.com/mbucchia/Quad-Views-Foveated/assets/26724958/edf0e4e6-1683-4f4e-94fd-2470f1e8c6fc)
![3](https://github.com/mbucchia/Quad-Views-Foveated/assets/26724958/c810de7e-0d2f-456c-9644-34f3ece37bd5)
![4](https://github.com/mbucchia/Quad-Views-Foveated/assets/26724958/d82e2473-6bc0-4a99-a703-8b57279d695c)

**Comment by mbucchia** [comment]
I'm not really sure what any of this means, but it really sounds like a game issue rather than an issue with Quad-Views-Foveated. Not something I have any control over.

**Comment by ytdlder** [comment]
Well, it for sure is a weird one, I give you that

**Comment by mbucchia** [comment]
I'm told the situation has improved in 2.9. Nonetheless this isn't anything that the foveated rendering code can improve. Closing.
