### ISSUE TITLE
DFR does not work since DCS 2.9

### ISSUE THREAD

**Issue by PatZab** [mbucchia/Quad-Views-Foveated#12]
Since the latest update of DCS today the DFR ingame does not work. It does not track my eyes, but it is more like Fixed Foveated Rendering. I have installed the latest version of Quad Views Foveated and also the latest version of PimaxXR, OpenXR Toolkit, and the QVF Companion App.

My Headset is the Pimax Crystal.

I did everything like in this Video [https://www.youtube.com/watch?v=A6g58RVPiUc](https://www.youtube.com/watch?v=A6g58RVPiUc). But it keeps fixed.

Maybe I have some settings wrong or is there an actual problem with DCS 2.9?

Thanks

**Comment by mbucchia-msft** [comment]
see workaround here: https://forum.dcs.world/topic/333666-dynamic-foveated-rendering-everything-in-one-page/?do=findComment&comment=5306921

**Comment by PatZab** [comment]
Thanks that helped! :)
