### ISSUE TITLE
GPU FRAME TIME REPORTED AS "0" IN OXRTK AND VERY LOW VALUE IN RECORDED FILE

### ISSUE THREAD

**Issue by WipeUout** [mbucchia/Quad-Views-Foveated#13]
When quad view is enabled, I am not getting a value for GPU Frame time in the overlay, it stays at 0.  If I record to a file, the values recorded are very low with a calculated average of about 10-11 or 0.011 ms.

App: DCS World 2.9 OB
HMD: Pimax 8kX, Pimax Client 1.16
PimaxXR 0.4.4, OXRTK 1.3.2, QUAD View 1.1.3

**Comment by mbucchia** [comment]
This is because quad views has Turbo mode by default which interferes with OpenXR Toolkit overlay. You can disable Turbo in quad views and enable it in OpenXR Toolkit instead.
