### ISSUE TITLE
Crash to desktop after removing headset

### ISSUE THREAD

**Issue by sevn10** [mbucchia/Quad-Views-Foveated#2]
Anytime I remove my Quest Pro and then put it back on to return to DCS the game will crash to desktop with Meta Foveated installed. My headset should be set to not pause on removal and my power down is set for 15 minutes instead of the default 15 seconds. 

[dcs.log](https://github.com/mbucchia/Meta-Foveated/files/11927763/dcs.log)

**Comment by mbucchia** [comment]
I haven't gotten any other report of this issue, so I'm inclined to think that it's very specific to your set up.

I suspect this might be a side effect of developer mode (aka a Meta bug?).

Try sending me the Meta-Foveated log file instead. 

And you might have better luck posting on this thread:
https://forum.dcs.world/topic/318095-foveated-rendering-support-for-dcs/page/8/#comments

**Comment by sevn10** [comment]
Thanks, I will post on the DCS forum thread, I must have missed that.

**Comment by mbucchia** [comment]
You actually did the right thing opening an issue here, but missed attaching the correct log. Per the discussion on the forum (and your log over there) it looks like you are not alone.

I'll take a closer week mid-July when some time opens up for me.

**Comment by mbucchia** [comment]
Per DCS forum - was this issue resolved after you re-enabled the guardian?

**Comment by sevn10** [comment]
I'll give this a try soon, I've been away most of the month.

**Comment by sevn10** [comment]
I'm happy to report that there are no more crashes after taking the Quest Pro off and putting it back on again when using version 1.0.1. I have tried with Guardian enabled and disabled, as well as Turbo Mode in the settings.cfg on and off.

**Comment by mbucchia** [comment]
This was fixed in 96aa408f1f30fbb05ba2976000d7a612a3d609c1.
