### ISSUE TITLE
Question - Quest Pro - how to check version or upgrade

### ISSUE THREAD

**Issue by LilBub** [mbucchia/Quad-Views-Foveated#4]
Hi,
The only uninstall option I see is for SteamVR.
I've debugging some issues I am having in DCS World with "CPU Bound" in red while flying in DCS.
I wanted to check the version I have installed
Thks

**Comment by mbucchia** [comment]
There's only been one version released, so you're on the latest :)

For removal instructions see here: https://github.com/mbucchia/Quad-Views-Foveated/wiki#removal

**Comment by LilBub** [comment]
The removal instructions show SteamVR with my Quest Pro doesn't use, fyi

Also, do we need to reinstall this program every time DCS Beta updates?  I was t sure if the files get overwritten.  Thanks

**Comment by mbucchia** [comment]
Where is the reference to SteamVR in removal?

![image](https://github.com/mbucchia/Quad-Views-Foveated/assets/69611560/07dfe08e-315a-4e7e-b281-d99b5b336eb2)

> Also, do we need to reinstall this program every time DCS Beta updates? I was t sure if the files get overwritten. Thanks

No this program isn't specific to DCS.

**Comment by LilBub** [comment]
My apologies. Thanks for your patience.
