### ISSUE TITLE
Installation breaks Unreal Engine OpenXR Integration

### ISSUE THREAD

**Issue by Blender-Alien** [mbucchia/Quad-Views-Foveated#5]
So I've been using this for DCS and having a blast,
but had a hard time finding out why Unreal Engine didn't work anymore in VR.
So basically regardless of if I'm interfacing with UE OpenXR (Engine Version doesn't matter, I tried 4.27 and 5.2)
with Virtual Desktop->SteamVR or Oculus OpenXR, the Headset is not being recognized and no data (tracking / image) is sent back and forth.
**The same thing with my Valve Index.**

_The fix is uninstall and reboot._

I'm not sure if anyone here can do something about this, but I thought I'd get the word out.

Additional Info:
- I'm on an RX 6750 XT, Windows 11
- Unity works perfectly fine

**Comment by mbucchia** [comment]
Hi, Can you share a log file? I've been using this with UE VR template, and even Pavlov VR (UE game) without issues.

**Comment by Blender-Alien** [comment]
Hi, which do you want (from what software) and how do I obtain it?

**Comment by Blender-Alien** [comment]
[Quad-Views-Foveated.log](https://github.com/mbucchia/Quad-Views-Foveated/files/12285225/Quad-Views-Foveated.log)

I think I found your log. I see some errors, and I double checked that DCS DFR works and Unreal Engine doesn't.

**Comment by Blender-Alien** [comment]
I read through the log and saw something about an unsupported graphics API, so I switched form DX12 to DX11 and now I have DFR in my Unreal Engine preview. The only thing that bugs me still, is that the unreal editor is painfully slow/laggy with the plugin installed. That was not the case without DFR (working or not) enabled

**Comment by mbucchia** [comment]
Ah the DX12 support. Sorry I completely forgot about this... yes all my UE testing was done forcing DX11 mode. I haven't written the DX12 code (yet).

I'm not sure about the editor slowness.... have to try myself or capture a trace.

**Comment by Blender-Alien** [comment]
Yeah, it's really just the editor. VR preview runs perfectly fine. Is there a way to disable DFR in the settings.cfg when using Unreal to disable it temporarirly? I check the docs and didn't find an on/off switch

**Comment by mbucchia** [comment]
I have options for changing settings per app, but not disabling. This might be possible though I have to make sure one can easily distinguish the editor vs the packaged app.

**Comment by mbucchia** [comment]
> Yeah, it's really just the editor. VR preview runs perfectly fine. Is there a way to disable DFR in the settings.cfg when using Unreal to disable it temporarirly? I check the docs and didn't find an on/off switch

Do you have some steps to repro? I just tried the VR Template in 5.1.1, and I can see Quad-Views-Foveated being loaded in the editor, but no session is started. Upon tracing calls, I see no calls being serviced (except for `xrPollEvent()` which is normal and free.
I don't see a way to distinguish that it's the editor running. I could look at the exe name, it's a little dirty. But first I want to make sure I have a repro.


Thanks,

**Comment by Blender-Alien** [comment]
I'm using Unreal 5.2.1, but iirc the same problem was there in Unreal 4.27.2 when I was trying out different version to find the problem. But this is only the case when using Link / Airlink and not Virtual Desktop (which does not support Eye tracking) even with DFR installed. Concerning steps to reproduce, I can open the template with airlink or link and the whole editor runs at 5 fps or something.

**Comment by mbucchia** [comment]
In c8d6f7d97e794efc457a4e5de6a73701985461de there is a new config file option to "un-advertise" the quad views mode for selected application. This will be documented in the Wiki.
