### ISSUE TITLE
Not an issue:  A question..

### ISSUE THREAD

**Issue by GayCavalier** [mbucchia/Quad-Views-Foveated#6]
I did have a question for you:

Does QuadViews permit having multiple regions? i.e. It'd be really great if we could have a peripheral region, a foveate region, and a "super foveate" region.. the use case would be as follows:
Foveate focus size 35%
Foveate resolution: 200% (i.e. 1.44)
Super foveate focus size: 10%
Super foveate resolution: 500%

i.e. it'd give you the opportunity to look at details and small objects far in the distance with better clarity without necessarily hurting performance too much. Evidently the new super foveate would need its own transition thickness too, but the vertical focus offset would be the same for the foveate region..

Thanks again!

GayCavalier aka /u/TallyMouse

**Comment by mbucchia** [comment]
Hey this is a good question however the answer is no :)

"quad views" (4 views) is designed specifically this way: https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#XR_VARJO_quad_views

> In this configuration each eye consists of two viewports of which one is smaller (in terms of field of view) of the other and fully included inside of the larger FoV one. The small FoV viewport however can have a higher resolution with respect to the same field of view in the outer viewport. 

There is no way to force 6 viewports total, and anyway it would not be a good idea: each view port costs some performance. Yes the overall foveation helps saving on the final _pixel_ count, but each viewport needs to draw geometry which has a cost on CPU.

4 viewports is a good compromise, 6 would cost too much on CPU.

**Comment by GayCavalier** [comment]
Ahh - I should have read more in advance.  I'll just have to wait for HexaViews to come out! ;-)

**Comment by mbucchia** [comment]
@GayCavalier  can you look at this ASAP please?

https://github.com/mbucchia/Quad-Views-Foveated/issues/8

This has caused a lot of issues today. Thanks!
